### ISSUE TITLE
Not able to add traffic layer

### ISSUE THREAD

**Issue by kulkarnipradnyas** [aviklai/react-leaflet-google-layer#14]

**Comment by aviklai** [comment]
@kulkarnipradnyas Hi, I think it's possible to add it.
I will check and update.

**Comment by aviklai** [comment]
Hi, I added this ability to the latest version.
You can use the property:

googleMapsAddLayers

To pass a list of layers you want to add, including the traffic layer like this:

```
<ReactLeafletGoogleLayer           
      googleMapsAddLayers={[{ name: 'TrafficLayer' }]}
/>
```

**Comment by kulkarnipradnyas** [comment]
![Screenshot 2020-11-03 at 7 56 00 PM](https://user-images.githubusercontent.com/13656893/97997090-9ac66200-1e0e-11eb-95d5-73b497013e06.png)

It gives error as this property does not exist in library 'react-leaflet-google-layer'
Do you have any other solution?

**Comment by aviklai** [comment]
Please check this example:
https://codesandbox.io/s/basic-usage-forked-iscjf

You will see that the traffic is visible.

**Comment by aviklai** [comment]
@kulkarnipradnyas which version of React Leaflet are you using? If you are using React Leaflet v3, please check the latest release of this library.

**Comment by kulkarnipradnyas** [comment]
@aviklai , thanks for example and apologies for late reply.yeah my library was not updated.

**Comment by aviklai** [comment]
Can you please add here a codesandbox with the issue?

**Comment by kulkarnipradnyas** [comment]
Sorry for late response.It worked fine.Marker shaking was happening because of flytoBound method while zooming instead of that used setView.Problem solved.
