### ISSUE TITLE
Support React v17

### ISSUE THREAD

**Issue by yuiseki** [aviklai/react-leaflet-google-layer#19]
## About

The current stable version of React is v17.
This packages cause error when install to project that needs React v17 because dependency has set to React v16.
(For example, Next.js stable version 10 needs react v17)

React v16 to v17 has no breaking change, no new features.
So I think there is no critical problem to upgrade v17.
https://reactjs.org/blog/2020/10/20/react-v17.html

## Workaround

`npm i react-leaflet-google-layer --force`

If you'd welcome a Pull Request, I'd like to send it to you later.

**Comment by aviklai** [comment]
@yuiseki Hi,

Of course - a PR is definitely welcome.
