### ISSUE TITLE
Google Maps is not loading

### ISSUE THREAD

**Issue by adithya1310** [aviklai/react-leaflet-google-layer#29]
Hello 

The google maps is not loading. getting the error on from this package. could you please check
![Screen Shot 2022-02-16 at 8 42 15 PM](https://user-images.githubusercontent.com/50845069/154394536-f3f3c09b-4c3a-4f7d-90d5-d1ba086bcb68.png)

**Comment by aviklai** [comment]
@adithya1310 Hi,

Can you please add a codesandbox with the issue?

**Comment by adithya1310** [comment]
Hey @aviklai  its not working with your example sandbox too
https://codesandbox.io/s/basic-usage-with-react-leaflet-v3-vx8fd

**Comment by bilemedimkq** [comment]
I am still experiencing the same problem, I use this package in the prod settings and it isn't working right now, can you please help?

**Comment by komitake** [comment]
Updating `leaflet.gridlayer.googlemutant` to latest version `0.13.5` will resolve this issue.
https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/-/issues/139

**Comment by aviklai** [comment]
Published a fix - version 2.0.5.
It works in the example now:
https://codesandbox.io/s/basic-usage-with-react-leaflet-v3-vx8fd

Publishing a fix for version 1 as well.

**Comment by bilemedimkq** [comment]
It is working now. Thanks!
