### ISSUE TITLE
Dynamic map type switch

### ISSUE THREAD

**Issue by siddharthkul** [aviklai/react-leaflet-google-layer#43]
Request for support for dynamic map type - "road | terrain ...etc"

Below is an example:

```
function LeafletTileLayer() {
  const [currentMapType, setCurrentMapType] = useState('terrain');
  useEffect(() => {
    setCurrentMapType('road');
  }, []);
  return (
    <ReactLeafletGoogleLayer useGoogMapsLoader={false} type={currentMapType} />
  );
}
```

**Comment by aviklai** [comment]
@siddharthkul Hi,

Dynamic map type is not supported by Leaflet.GridLayer.GoogleMutant.
I think that the best way to achieve this functionality will be to change the key of the component based on the type, like this:
https://codesandbox.io/s/basic-usage-with-react-leaflet-v3-forked-jb2ltg

**Comment by siddharthkul** [comment]
Aah ofcourse. Appreciate it ! Marking this as closed.
