### ISSUE TITLE
Can't specify particular VERSION for google maps API

### ISSUE THREAD

**Issue by VadimKovalenkoSNF** [aviklai/react-leaflet-google-layer#49]
Hi! I'm trying to render the map using specific version of Google Maps API listed in https://developers.google.com/maps/documentation/javascript/releases, but always get the most recent javascript (In the example below it is `3.59.3` for [12 December 2024](https://developers.google.com/maps/documentation/javascript/releases#2024-12-12))

![image](https://github.com/user-attachments/assets/94952835-a280-4008-b477-d4ba1e587138)

Codesandbox link [here](https://codesandbox.io/p/sandbox/basic-usage-forked-4r92yc). Any thoughts about it?

**Comment by vladsha-dev** [comment]
+ 1

**Comment by roman-stolar** [comment]
The same issue for me.

**Comment by aviklai** [comment]
Looks like it's not available anymore on Google's side:
https://developers.google.com/maps/documentation/javascript/versions

Try loading version 3.56 - and you will see it works:
`<ReactLeafletGoogleLayer googleMapsLoaderConf={{ version: "3.56" }} />`

![image](https://github.com/user-attachments/assets/bfa6f93d-4b16-46af-b270-988172fb40a2)

**Comment by aviklai** [comment]
![image](https://github.com/user-attachments/assets/8c7ab74b-1705-45b7-ae07-cbcf9deb4621)

**Comment by VadimKovalenkoSNF** [comment]
Thanks @aviklai ! I've tried `3.57.12`, it works (though I've got `3.57.13` in DevTools).
.
![image](https://github.com/user-attachments/assets/9ac311cb-2367-4024-95d6-dc803796e050)

**Comment by roman-stolar** [comment]
Thank's it also work for me. @aviklai
